name: update catalog every sunday

on:
  push
  
    
jobs:
  build:
    name: Update the proofread hfml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip pip install pathlib'
        
    - name: Update the proofread hfml
      run: |
        from pathlib import Path

        def get_vol_text(vol_path):
            vol_text = ''
            page_paths = list(vol_path.iterdir())
            page_paths.sort()
            for page_path in page_paths:
                if page_path.suffix == ".txt":
                    page_num = int(page_path.stem)
                    page_content = page_path.read_text(encoding='utf-8')
                    vol_text += f'〔{page_num}〕\n{page_content}\n'
            return vol_text

        if __name__ == "__main__":
            vol_paths = list(Path('./proofread-derge-tengyur/esukhia_tengyur/').iterdir())
            vol_paths.sort()
            for vol_path in vol_paths:
                vol_text = get_vol_text(vol_path)
                Path(f'./proofread-derge-tengyur/proofread_tengyur_hfml/{vol_path.stem}.txt').write_text(vol_text, encoding='utf-8')
      shell: python
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v8
      with:
        author_name: kaldan007
        author_email: kaldantenzin@gmail.com
        message: 'proofread hfml updated'
        add: '*'